"""initial PostgreSQL publication schema"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision = '0001_postgresql'
down_revision = None
branch_labels = None
depends_on = None
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_type', sa.String(length=30), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=True),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_class', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("state IN ('queued','running','succeeded','failed','cancelled')", name='job_state'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('job_filter', 'jobs', ['state', 'created_at'], unique=False)
    op.create_table('publication_attempts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('event_uuid', sa.String(length=200), nullable=False),
    sa.Column('date_uuid', sa.String(length=200), nullable=False),
    sa.Column('date_slug', sa.String(length=200), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('mutation_stage', sa.String(length=40), nullable=True),
    sa.Column('target_ref', sa.String(length=200), nullable=True),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('remote_id', sa.String(length=200), nullable=True),
    sa.Column('remote_url', sa.Text(), nullable=True),
    sa.Column('error_class', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("mutation_stage IS NULL OR mutation_stage IN ('facebook_photo','facebook_feed','mastodon_media','mastodon_status','instagram_container','instagram_publish')", name='mutation_stage'),
    sa.CheckConstraint("platform IN ('facebook','instagram','mastodon')", name='attempt_platform'),
    sa.CheckConstraint("state IN ('reserved','publishing','remote_succeeded','published','failed','cancelled')", name='attempt_state'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('active_publication', 'publication_attempts', ['platform', 'date_uuid'], unique=True, postgresql_where=sa.text("state IN ('reserved','publishing','remote_succeeded')"))
    op.create_index('attempt_date', 'publication_attempts', ['date_uuid'], unique=False)
    op.create_index('attempt_filter', 'publication_attempts', ['platform', 'state', 'created_at'], unique=False)
    op.create_table('publications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('attempt_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('event_uuid', sa.String(length=200), nullable=False),
    sa.Column('date_uuid', sa.String(length=200), nullable=False),
    sa.Column('date_slug', sa.String(length=200), nullable=False),
    sa.Column('remote_id', sa.String(length=200), nullable=False),
    sa.Column('remote_url', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['publication_attempts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id')
    )
    op.create_index('publication_date', 'publications', ['platform', 'date_uuid'], unique=False)
    op.create_index('publication_time', 'publications', ['published_at'], unique=False)
    # ### end Alembic commands ###
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('publication_time', table_name='publications')
    op.drop_index('publication_date', table_name='publications')
    op.drop_table('publications')
    op.drop_index('attempt_filter', table_name='publication_attempts')
    op.drop_index('attempt_date', table_name='publication_attempts')
    op.drop_index('active_publication', table_name='publication_attempts', postgresql_where=sa.text("state IN ('reserved','publishing','remote_succeeded')"))
    op.drop_table('publication_attempts')
    op.drop_index('job_filter', table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
